#!/usr/bin/env python3
"""Generate every tool-specific adapter from the single canon.

  build_adapters.py          write adapters/
  build_adapters.py --check  exit 1 if adapters/ is stale (used in CI)

Outputs:
  adapters/CLAUDE.md                 Claude Code: always-on mindset + how to load moments as skills
  adapters/AGENTS.md                 the AGENTS.md convention (same content)
  adapters/cursor/*.mdc              Cursor rules: one always-on, one per moment (agent-requested)
  adapters/system-prompt.txt         for anything with a system prompt: mindset + guardrails + voice + lexicon + index
  adapters/system-prompt-full.txt    the whole canon, concatenated, for long-context agents
  adapters/llms.txt                  index for agents that fetch by path
  adapters/copilot-instructions.md   GitHub Copilot: drop in as .github/copilot-instructions.md
  adapters/openai-custom-gpt.txt     OpenAI custom GPT instructions (fits the 8,000 char limit)
  adapters/codex-config.toml         Codex CLI MCP snippet for the context layer
  SKILL.md (root)                    the whole repo as one Agent Skill (npx skills, Claude Code plugin)
  GEMINI.md (root)                   Gemini CLI extension context file
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "adapters"
HEADER = "<!-- GENERATED by scripts/build_adapters.py from the canon. Edit the source files, not this. -->\n\n"


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def body(rel):
    """File content without YAML frontmatter."""
    t = read(rel)
    if t.startswith("---"):
        end = t.find("\n---", 3)
        if end != -1:
            t = t[end + 4:]
    return t.strip() + "\n"


def frontmatter(rel):
    t = read(rel)
    fm = {}
    if t.startswith("---"):
        end = t.find("\n---", 3)
        for line in t[3:end].strip().splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip().strip('"')
    return fm


def moments():
    items = []
    for d in sorted((ROOT / "moments").iterdir()):
        s = d / "PLAYBOOK.md"
        if s.exists():
            fm = frontmatter(s.relative_to(ROOT).as_posix())
            items.append((d.name, fm.get("description", ""), s.relative_to(ROOT).as_posix()))
    return items


def principles():
    items = []
    for p in sorted((ROOT / "principles").glob("*.md")):
        title = next((l[2:].strip() for l in p.read_text().splitlines() if l.startswith("# ")), p.stem)
        items.append((title, p.relative_to(ROOT).as_posix()))
    return items


def index_block():
    lines = ["## Index (load on demand)\n", "### Moments (one playbook per situation)\n"]
    for name, desc, path in moments():
        lines.append(f"- `{path}`: {desc}")
    lines.append("\n### Principles\n")
    for title, path in principles():
        lines.append(f"- `{path}`: {title}")
    lines.append("\n### Always available\n")
    for rel, why in [
        ("voice/VOICE.md", "how to sound"),
        ("voice/LEXICON.md", "banned words, phrases, openers, patterns"),
        ("voice/EXEMPLARS.md", "annotated replies to imitate"),
        ("voice/channels/", "per-channel register"),
        ("guardrails/never.md", "hard rules"),
        ("guardrails/authority.md", "the nudge-first gate for sensitive actions"),
        ("guardrails/escalation.md", "when and how to bring in a human"),
        ("context/CONTRACT.md", "what to read about the customer before speaking"),
        ("delight/", "when and how to do the unreasonable thing"),
        ("retention/", "signals, save plays, exit, win-back"),
        ("onboarding/", "the first hundred days"),
        ("evals/", "how replies are graded"),
    ]:
        lines.append(f"- `{rel}`: {why}")
    return "\n".join(lines) + "\n"


def loading_rules():
    return """## How to use this canon

1. `MINDSET.md` and `PRECEDENCE.md` are always loaded. They are who you are.
2. Before replying to anyone, satisfy `context/CONTRACT.md` through the adapter for your context layer. If a context MCP server is connected (for example a tool like `ask_account`), call it before drafting, every time. Read the file before you greet the guest. If no context tools are connected, treat it as a first conversation and never pretend to know.
3. Identify the moment. Load exactly one playbook from `moments/`. Load a second only if the thread spans two moments.
4. Draft in the voice (`voice/VOICE.md`), check against `voice/LEXICON.md`. If it fails, rewrite from source; never patch the draft.
5. Anything in a sensitive dimension (personal data, money, access, deletion, anything leaving the building) gets a nudge to the operator before you act. See `guardrails/authority.md`. Act only inside an explicit grant.
6. After a substantive interaction, write the touch note back through the adapter.
7. If a company overlay is present (`overlay/`), it sits between this canon and the conversation. It may narrow, never loosen, the guardrails.
"""


def claude_md():
    return (
        HEADER
        + "# Front of House\n\n"
        + body("MINDSET.md").split("\n", 1)[1].strip() + "\n\n"
        + body("PRECEDENCE.md") + "\n"
        + body("guardrails/never.md") + "\n"
        + loading_rules() + "\n"
        + index_block()
    )


def cursor_rules():
    files = {}
    always = (
        "---\n"
        "description: \"Front of House, the hospitality mindset for any customer-facing agent. Always on.\"\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n"
        + body("MINDSET.md").split("\n", 1)[1].strip() + "\n\n"
        + body("PRECEDENCE.md") + "\n"
        + body("guardrails/never.md") + "\n"
        + body("guardrails/authority.md") + "\n"
        + loading_rules()
    )
    files["front-of-house.mdc"] = always
    voice = (
        "---\n"
        "description: \"Front of House voice and lexicon. Load when drafting anything a customer will read.\"\n"
        "globs:\n"
        "alwaysApply: false\n"
        "---\n"
        + body("voice/VOICE.md") + "\n" + body("voice/LEXICON.md")
    )
    files["front-of-house-voice.mdc"] = voice
    for a in sorted((ROOT / "context" / "adapters").glob("*.md")):
        if a.stem == "TEMPLATE":
            continue
        files[f"context-{a.stem}.mdc"] = (
            "---\n"
            f"description: {yq(f'How to satisfy the Front of House context contract through {a.stem}. Load when a customer conversation needs the customer file.')}\n"
            "globs:\n"
            "alwaysApply: false\n"
            "---\n"
            + body("context/CONTRACT.md") + "\n" + body(a.relative_to(ROOT).as_posix())
        )
    for name, desc, path in moments():
        files[f"moment-{name}.mdc"] = (
            "---\n"
            f"description: {yq(desc)}\n"
            "globs:\n"
            "alwaysApply: false\n"
            "---\n"
            + body(path)
        )
    return files


def system_prompt():
    return (
        "FRONT OF HOUSE\n\n"
        + body("MINDSET.md").split("\n", 1)[1].strip() + "\n\n"
        + body("PRECEDENCE.md") + "\n"
        + body("guardrails/never.md") + "\n"
        + body("guardrails/authority.md") + "\n"
        + body("guardrails/escalation.md") + "\n"
        + body("context/CONTRACT.md") + "\n"
        + body("voice/VOICE.md") + "\n"
        + body("voice/LEXICON.md") + "\n"
        + loading_rules() + "\n"
        + index_block()
    )


def system_prompt_full():
    parts = [system_prompt(), "\n\n# PRINCIPLES\n"]
    for _, path in principles():
        parts.append(body(path))
    parts.append("\n\n# MOMENTS\n")
    for name, _, path in moments():
        parts.append(f"\n## Moment: {name}\n\n" + body(path))
    for rel in ["voice/EXEMPLARS.md", "delight/PHILOSOPHY.md", "delight/catalog.md", "retention/signals.md", "retention/save-plays.md", "onboarding/first-100-days.md"]:
        if (ROOT / rel).exists():
            parts.append("\n" + body(rel))
    return "\n".join(parts)


def yq(text):
    """Quote a string for YAML frontmatter."""
    import json
    return json.dumps(text)


def skill_md():
    """Root SKILL.md: the whole repo is one Agent Skill (npx skills, Claude Code plugin)."""
    desc = ("Front of House: the hospitality mindset for any customer-facing work. Load before replying to, "
            "onboarding, retaining, or delighting a customer. Reads the customer's file first, answers first, "
            "nudges before anything sensitive, never invents policy.")
    return (
        "---\n"
        "name: front-of-house\n"
        f"description: {yq(desc)}\n"
        "---\n\n"
        "# Front of House\n\n"
        "This directory is the whole canon. Paths below are relative to this file.\n\n"
        + body("MINDSET.md").split("\n", 1)[1].strip() + "\n\n"
        + body("PRECEDENCE.md") + "\n"
        + body("guardrails/never.md") + "\n"
        + loading_rules() + "\n"
        + index_block()
    )


def custom_gpt():
    """Compact instructions for OpenAI custom GPTs (8,000 character limit). The rest is uploaded as knowledge."""
    text = (
        "FRONT OF HOUSE (compact). The full canon is in the uploaded knowledge files; consult them by name.\n\n"
        + body("MINDSET.md").split("\n", 1)[1].strip() + "\n\n"
        + body("PRECEDENCE.md") + "\n"
        + body("guardrails/never.md") + "\n"
        + "How to use the knowledge files: read context/CONTRACT.md before replying (ask the operator for the "
          "customer's file if you have no tools); pick one moments/<slug>/PLAYBOOK.md; draft in voice/VOICE.md; "
          "avoid everything in voice/LEXICON.md; nudge the operator before any sensitive action per "
          "guardrails/authority.md.\n"
    )
    limit = 8000
    if len(text) > limit:
        text = text[: limit - 60].rsplit("\n", 1)[0] + "\n\n(Truncated to the 8,000 character limit; see knowledge files.)\n"
    return text


def codex_toml():
    return (
        "# Codex CLI: add to ~/.codex/config.toml to connect the Moonbase context layer.\n"
        "# Put the key in your environment as MOONBASE_MCP_KEY. Never write it here.\n\n"
        "[mcp_servers.moonbase]\n"
        'url = "https://yavin.moonbase.ai/mcp"\n'
        'bearer_token_env_var = "MOONBASE_MCP_KEY"\n'
    )


def check_versions():
    import json
    v = (ROOT / "VERSION").read_text().strip()
    bad = []
    for rel in [".claude-plugin/plugin.json", "gemini-extension.json"]:
        if json.loads((ROOT / rel).read_text())["version"] != v:
            bad.append(rel)
    m = json.loads((ROOT / ".claude-plugin/marketplace.json").read_text())
    if any(pl["version"] != v for pl in m["plugins"]):
        bad.append(".claude-plugin/marketplace.json")
    return bad


def llms_txt():
    lines = ["# Front of House", "", "> A hospitality canon any customer-facing agent can load. Start with MINDSET.md.", ""]
    lines.append("## Core")
    for rel in ["MINDSET.md", "PRECEDENCE.md", "guardrails/never.md", "guardrails/authority.md", "context/CONTRACT.md", "voice/VOICE.md", "voice/LEXICON.md"]:
        lines.append(f"- [{rel}]({rel})")
    lines.append("")
    lines.append("## Moments")
    for name, desc, path in moments():
        lines.append(f"- [{name}]({path}): {desc}")
    lines.append("")
    lines.append("## Principles")
    for title, path in principles():
        lines.append(f"- [{title}]({path})")
    return "\n".join(lines) + "\n"


def build():
    files = {
        ROOT / "SKILL.md": skill_md(),
        ROOT / "GEMINI.md": claude_md(),
        OUT / "CLAUDE.md": claude_md(),
        OUT / "copilot-instructions.md": claude_md(),
        OUT / "openai-custom-gpt.txt": custom_gpt(),
        OUT / "codex-config.toml": codex_toml(),
        OUT / "AGENTS.md": claude_md(),
        OUT / "system-prompt.txt": system_prompt(),
        OUT / "system-prompt-full.txt": system_prompt_full(),
        OUT / "llms.txt": llms_txt(),
    }
    for name, content in cursor_rules().items():
        files[OUT / "cursor" / name] = content
    return files


def main(argv):
    files = build()
    if "--check" in argv:
        bad = check_versions()
        if bad:
            print("version mismatch with VERSION file:", ", ".join(bad))
            return 1
        stale = [p for p, c in files.items() if not p.exists() or p.read_text(encoding="utf-8") != c]
        extra = [p for p in OUT.rglob("*") if p.is_file() and p not in files and p.name != "README.md"]
        if stale or extra:
            for p in stale:
                print(f"stale: {p.relative_to(ROOT)}")
            for p in extra:
                print(f"orphan: {p.relative_to(ROOT)}")
            print("Run: python3 scripts/build_adapters.py")
            return 1
        print("adapters up to date")
        return 0
    for p, c in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(c, encoding="utf-8")
        print(f"wrote {p.relative_to(ROOT)} ({len(c.split())} words)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
